### ISSUE TITLE
Init: Initialize only a certain folder, ignoring all events other than push

### ISSUE THREAD

**Issue by JacobDanS** [YappyBots/YappyGithub#44]
I wanted to add https://github.com/JacobDanS/Skeleton/tree/gh-pages/examples/landing but I found out that you can't do folders. Please add it later in the rewrite.

**Comment by datitisev** [comment]
Discuss: Do we want to have to add something to the URL or to be able to init just the folder (thus ignoring events other than `push`) from Discord?

**Comment by Kore-Development** [comment]
There would be an option for only the folder or to make it the whole repo. Just init the folder

**Comment by Kore-Development** [comment]
I'm JacobDanS

**Comment by Kore-Development** [comment]
This account is a second account

**Comment by datitisev** [comment]
I think I'm not going to add this, as it would go further than I want it the bot to be. You can accomplish this with using a subrepo, however.
