### ISSUE TITLE
Event: Added / Removed repo from organization.

### ISSUE THREAD

**Issue by Kore-Development** [YappyBots/YappyGithub#46]
Can you add a message for when someone turns on and off the github pages and changes the theme? And also for orgs can u add a message for when someone adds or removes a repo

**Comment by Kore-Development** [comment]
Also when someone turns on github pages I would like it if you could add a image to the message that is a preview of the site if its possible

**Comment by datitisev** [comment]
Actually, I don't think that's possible....

**Comment by Kore-Development** [comment]
It's ok

**Comment by datitisev** [comment]
I'll look into it.

**Comment by datitisev** [comment]
Hm, unfortunately, I cannot do the part of Github Pages and theme and all. (the theme is a file, btw). 
However, i can do the add repo and remove.

**Comment by datitisev** [comment]
Hm, I think I did that with the `repository` event on the rewrite. I'll reopen this if it's not.
