### ISSUE TITLE
Command: Search

### ISSUE THREAD

**Issue by Kore-Development** [YappyBots/YappyGithub#48]
Can you add a command to search for users, repos, and orgs?

**Comment by datitisev** [comment]
User search done.

![image](https://user-images.githubusercontent.com/6401250/27999115-f87c4f02-64e6-11e7-9198-50f5a499e510.png)

**Comment by datitisev** [comment]
Repo search done

![image](https://user-images.githubusercontent.com/6401250/28137093-0ac51358-671a-11e7-86f9-add21323a528.png)

**Comment by datitisev** [comment]
Cannot make search of organizations.

**Comment by datitisev** [comment]
Added in 42d26b5b8148140de7703fabf07dae4c33c5e0ea.
