### ISSUE TITLE
No more events recived after discord category.

### ISSUE THREAD

**Issue by tsbreuer** [YappyBots/YappyGithub#50]
Ever since i organized discord channels in categories i stopped reciving the updates. 

I checked on Github webhooks and its getting error 302.

**Header:**
> Request URL: http://discordjsrewritetrello-datitisev.rhcloud.com/
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/0e7adb7
X-GitHub-Delivery: 4d9060b0-ad61-11e7-844b-0ef4730cd5b8
X-GitHub-Event: page_build

All events failing:
https://puu.sh/xUjSG/799fd3de25.png

**Comment by tsbreuer** [comment]
Nevermind, i just checked the response.

**Comment by tsbreuer** [comment]
Apparently not, on updated URL its giving Error 404.

**Comment by datitisev** [comment]
The new URL is https://www.yappybots.tk. Openshift v2 died on September 30th.
Sorry about all the confusion. I tried to use the announce command on the bot to send a message on all channels with repos, but it seems like it failed.
