### ISSUE TITLE
Spam caused by star events

### ISSUE THREAD

**Issue by Gamedev1909** [YappyBots/YappyGithub#51]
hi we have a spam issue when a user stars the github and then stars it and does it over and over it spams the discord page where yappy reports 
![untitled](https://user-images.githubusercontent.com/18043258/33580113-57a592ea-d922-11e7-91b0-3ff46253654b.png) here is a image

**Comment by MrCK1** [comment]
@Gamedev1909 It's not a problem with Yappy, this is a problem with Github itself. You should just close this :)

**Comment by Gamedev1909** [comment]
no i rather it gets fixed by the bot maker then wait endless days for github

**Comment by datitisev** [comment]
@Gamedev1909 You can disable star updates by going into the webhook settings and disabling "watch".

**Comment by datitisev** [comment]
Also happened to me, seems like someone made a bot and started spamming, because this user doesn't exist. https://github.com/FUCKYOUEATDICKBITCH is 404
![image](https://user-images.githubusercontent.com/6401250/33582530-acf34e30-d923-11e7-813a-45397cbb8ad8.png)

**Comment by MrCK1** [comment]
@Gamedev1909 You can close this now.

**Comment by datitisev** [comment]
Please, feel free to reopen if you are not satisfied with my answer.
