### ISSUE TITLE
When title of issue is changed, bot will answer with "{author}/{repository}: [object Object]"

### ISSUE THREAD

**Issue by mostm** [YappyBots/YappyGithub#52]
![image](https://user-images.githubusercontent.com/23155159/34189513-9eb054d0-e55d-11e7-9b0b-b986285ad714.png)
![image](https://user-images.githubusercontent.com/23155159/34189526-b1c88f60-e55d-11e7-8bea-e976f5263b0f.png)

**Comment by datitisev** [comment]
Related to #39

**Comment by tlm-2501** [comment]
Is this in some way related to the defined-but-not-used function `EditedIssue` in `Github/Issues.js`? I have no way of testing this, unfortunately, but that seems like it's connected. As a side note, there are two used (but not defined) functions present in the file as well, `LabeledIssue` and `UnlabeledIssue`. Apologies if unrelated.

**Comment by datitisev** [comment]
Hm, that would make sense.
I think I fixed it in https://github.com/YappyBots/YappyGithub/commit/d8130215cc382ee7d92c8748bba353404cdadff9, let me know if it happens again.
