### ISSUE TITLE
config: cannot set prefix with spaces (see comments)

### ISSUE THREAD

**Issue by tablatronix** [YappyBots/YappyGithub#55]
how does prefix work ?

` Successfully set config key prefix to 'g'`

`g! help` does nothing

**Comment by datitisev** [comment]
@tablatronix The default prefix is `G! `. By setting a custom prefix for the server, you can use it like `PREFIXCOMMAND`, i.e. `ghelp in your case.

Please use Discord for help on any of the Yappy Bots.

**Comment by tablatronix** [comment]
Thanks, I did not catch the with space remark meant the prefix . Where in discord? The channel i am on says read only

**Comment by tablatronix** [comment]
How can I set space in custom?

**Comment by datitisev** [comment]
@tablatronix Hm, channel shouldn’t be read only, I’ll check why.

You *should* be able to set it with a space with either `G! conf set prefix “g “` or `G! conf set prefix ‘g ‘`.
If neither works, please let me know.

**Comment by tablatronix** [comment]
I was on announcements ... lol

**Comment by tablatronix** [comment]
It includes the quotes as prefix

` Successfully set config key prefix to '‘gh'``
`Successfully set config key prefix to '“gh'`

**Comment by datitisev** [comment]
Hm, it may be because of the type of quote. I’ll try to make it so any quote works... if I can.

**Comment by tablatronix** [comment]
any luck ?
I tried several quote types

**Comment by tablatronix** [comment]
single quotes works

`G! conf set prefix 'gh '`
