### ISSUE TITLE
pr pulls issues unrelated

### ISSUE THREAD

**Issue by tablatronix** [YappyBots/YappyGithub#56]
eg. G! pr #1157 pulls in not related issue #1153

**Comment by datitisev** [comment]
@tablatronix Can you explain yourself a bit more, maybe a screenshot...?

**Comment by tablatronix** [comment]
Hm its working now, I will screenshot it happens again, I cleared it already

**Comment by datitisev** [comment]
Ok, just let me know if it happens again.
