### ISSUE TITLE
docs do not match help?

### ISSUE THREAD

**Issue by tablatronix** [YappyBots/YappyGithub#58]
readme.md does not match !G help

`issues search <query>`, vs help just says issue.

```
Use `G! help <command>` for details

PUBLIC
clean    = clean the messages of the bot found in the number provided
issue    = Search issues or get info about specific issue
pr       = Search pull requests or get info about specific PR
release  = Get info about a release
help     = you all need some help
invite   = invite yappy to your server and some instructions
ping     = ping, pong
stats    = Shows some stats of the bot... what else?

ADMIN
conf     = configure some settings for this server
init     = Initialize repo events on the channel.
remove   = Remove Github repo events on the channel
say      = the bot says the text you want it to say
```

**Comment by tablatronix** [comment]
ahh readme is wrong

`issues search <query> - search issues by any field in the global repo`

should be
`issue search <query> - search issues by any field in the global repo`

**Comment by tablatronix** [comment]
also maybe change the help output to 

issue    = 'search' issues or get info about specific issue
pr       =  'search' pull requests or get info about specific PR

**Comment by datitisev** [comment]
That read me is outdated, please refer to the output of the help command.
