### ISSUE TITLE
Ignore case for entire prefix

### ISSUE THREAD

**Issue by ldilley** [YappyBots/YappyGitHub#59]
#53 was resolved by adding the following:

```js
let command = content.split(' ')[0].toLowerCase();
```

The problem with this is in cases such as setting the prefix to "!g" or "!g ". Only the first character's case in the string/prefix prior to the delimiter is ignored. In other words, Yappy is unresponsive to "!G ..." in this context. The entire string/prefix prior to the space delimiter should be case insensitive to avoid such issues.

**Comment by ldilley** [comment]
Correct, sir.

**Comment by dsevillamartin** [comment]
The bot no longer uses a prefix -- you must ping it (due to DIscord's changes regarding bots' ability to read all messages).
