### ISSUE TITLE
What docs template are you using?

### ISSUE THREAD

**Issue by Purpzie** [YappyBots/YappyGithub#62]
I've noticed that yours are organized the same way as the [discord.js](https://discord.js.org/#/docs/main/stable/general/welcome) docs. Is there a template or an open-sourced version of it around? It's very nice.

**Comment by datitisev** [comment]
You can check it out at https://github.com/discordjs/website.
You will need the custom doc generator, however, available at https://github.com/discordjs/docgen.
You can either check this repository or [discord.js](https://github.com/discordjs/discord.js) to see how to implement it using TravisCI.
