### ISSUE TITLE
Bug: Markdown being applied on PR Titles unintentionally

### ISSUE THREAD

**Issue by AniLeo** [YappyBots/YappyGitHub#64]
PR Titles need to be escaped somehow, if the title contains elements from markdown it will display those as markdown effects. 

For example, when renaming a PR that has _ in it, the italic applied in the bot will break.
`Yappy, the Github Monitor: RPCS3/rpcs3: :tools: AniLeo renamed issue #5219 to _AppImage: Missing 'CXXABI1.3.11', libstdc++.so.6 (Debian 9)`

![image](https://user-images.githubusercontent.com/10283761/46545428-3dbdf200-c8be-11e8-8361-de17717f71cb.png)

https://github.com/RPCS3/rpcs3/issues/5219 correct title is `AppImage: Missing 'CXXABI_1.3.11', libstdc++.so.6 (Debian 9) `

**Comment by dsevillamartin** [comment]
Fixed
