### ISSUE TITLE
Readme.md Fix

### ISSUE THREAD

**Issue by Deniernal354** [YappyBots/YappyGithub#65]
Enable widgets on your guild so the embed on the 1st line in readme.md can work. 

1. Go to your server click on its name.
2. Select server settings
3. Go to widget.
4. Turn on the switch that says enable server widget.

-------------------------------------------------------------------------------------------------------------------
**FIRST STEP**

![image](https://user-images.githubusercontent.com/31352787/47638101-b1c28180-db6e-11e8-84e3-dfdaa27f4078.png)

---------------------------------------------------

**SECOND STEP**

![image](https://user-images.githubusercontent.com/31352787/47638143-d0287d00-db6e-11e8-8004-94b27b863a34.png)

---------------------------------------------------

**THIRD STEP**

![image](https://user-images.githubusercontent.com/31352787/47638197-f0583c00-db6e-11e8-9a82-1bfcba5996cc.png)

---------------------------------------------------

**FOURTH STEP**

![image](https://user-images.githubusercontent.com/31352787/47638226-01a14880-db6f-11e8-8198-86649eb3b9b8.png)

 TURN THAT ON
---------------------------------------------------

**Comment by datitisev** [comment]
Odd, I thought I had it enabled already. Thanks 😁.
