### ISSUE TITLE
Bot is posting draft releases as published

### ISSUE THREAD

**Issue by pkmnfrk** [YappyBots/YappyGitHub#66]
![image](https://user-images.githubusercontent.com/1333816/56829236-33028480-6831-11e9-9956-ba22a2985a6f.png)

Recently (no sooner than April 11, no later than April 24), Yappy began posting draft releases in my channel as though they were published. This would happen any time I modify the text of the release, but not when modifying attachments.

**Comment by datitisev** [comment]
Hm, ok, thanks for the heads up. I'll look into it at some point.

**Comment by insuusvenerati** [comment]
This doesn't appear to be happening anymore. 
The event now shows as `An unknown event (release/created) has been emitted from repository`

**Comment by dsevillamartin** [comment]
hm whoops

**Comment by dsevillamartin** [comment]
Fixed
