### ISSUE TITLE
"Ping, pong! Webhook is set up!" no longer appearing

### ISSUE THREAD

**Issue by oddMLan** [YappyBots/YappyGithub#73]
So we were going through a Discord webhook directly but that seemed to mess up Yappy, and changed the payload url to `https://www.yappybots.tk` as instructed. Then sent a test through Github, which repeated the last PR in the repo. (simulating a PR, as the manual says, I guess).

But I remember (and by checking the old logs) that Yappy would let you know when the hook was working. It was a useful message to know to which events it was listening to.

**Comment by datitisev** [comment]
The `ping` event is only sent once - when the webhook on GitHub is created. If you edit the URL to fix it, it won't resend it.

**Comment by oddMLan** [comment]
Oh, okay, I didn't know that. Maybe that piece of info should be put somewhere. Thanks for the prompt response :)
