### ISSUE TITLE
Embedded format GitHub functionality not documented, creates confusion

### ISSUE THREAD

**Issue by oddMLan** [YappyBots/YappyGitHub#74]
So I mentioned in #73 that we had a situation in which we had to get rid of the Discord webhook and change the payload url to Yappy's instead. What happened was that the Discord webhook (that posts as "GitHub [bot]") was listening to the Yappy events, somehow. Eg. Yappy was already listening to **project64/project64** and the Discord Webhook was set up to listen to **mupen64plus/mupen64plus-core** and **mupen64plus/mupen64plus-rsp-hle**. Then Yappy stopped responding completely and the Discord webhook (named **mupen64plus Github** for that purpose) started posting the events of the Project64 repo. Is it common knowledge that one shouldn't mix Yappy with other webhooks? Or this shouldn't happen?

**Comment by datitisev** [comment]
Not sure what you are saying. The Discord /github webhook is independent from Yappy.

**Comment by oddMLan** [comment]
Exactly, so why is this happening? The Discord/github webhook  shouldnt interfere with Yappy, yet this is what we observed.

**Comment by datitisev** [comment]
Could you provide screenshots? I'm not sure exactly of what situation you are describing just by reading it.

**Comment by oddMLan** [comment]
Many thanks to kind @datitisev on the Yappy Discord server, helped me to figure out what was happening! And no thanks to the loser who downvoted me.

So it turns out when you do `G! init user/repo` you get the following message:
```
To use webhooks and have a nicer GitHub log, create a webhook in this channel called "Yappy" or "Github" and give the bot MANAGE WEBHOOKS permission in this channel
```
So in truth what was going on was that Yappy hijacked the **mupen64plus Github** webhook to use the so-called "nicer" format because it had "Github" in its name. The nicer format looks identical to the native Github bot, so I couldn't tell them apart. This webhook was simultaneously being used by the mupen64plus repo to push events into. This was most definitely not what I intended, so it got confusing. Aside that message when you init a repo, this functionality isn't documented anywhere. I'll go ahead and rename this issue until this behavior is documented on the website, and a warning like the following is added:
```
Unintended effect: If you create a Discord webhook to push events into with "Github" in the name Yappy will use it for the prettier embedded format, so if your server has webhooks separate from Yappy make sure they don't use "Github" in the name to avoid confusion.
```

**Comment by dsevillamartin** [comment]
This no longer applies because it's now a configuration setting.
